version: "{build}"

clone_depth: 1

environment:
  HUNSPELL_VERSION: v1.7.2

install:
  - git clone --depth 1 -b %HUNSPELL_VERSION% https://github.com/hunspell/hunspell.git
  - set PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;C:\msys64\bin;C:\msys64\usr\bin;%PATH%;

before_build:
  - cd hunspell
  - ps: $env:GITCOMMIT_FULL = git rev-parse HEAD

build_script:
  - bash C:/msys64/usr/bin/autoreconf -vfi
  - bash configure --prefix=C:/Hunspell
  - make

after_build:
  - make install
  - 7z a %APPVEYOR_BUILD_FOLDER%\hunspell-%HUNSPELL_VERSION%.7z C:\Hunspell
  - ps: |
      $env:ARTIFACT_HASH = (Get-FileHash -Algorithm SHA256 $env:APPVEYOR_BUILD_FOLDER\hunspell-$env:HUNSPELL_VERSION.7z).Hash
      "$env:ARTIFACT_HASH  hunspell-$env:HUNSPELL_VERSION.7z" | Out-File -Encoding ascii -File $env:APPVEYOR_BUILD_FOLDER\sha256sum.txt

artifacts:
  - path: hunspell-$(HUNSPELL_VERSION).7z
    name: Hunspell binary archive
  - path: sha256sum.txt
    name: SHA256 hash of Hunspell binary archive

deploy:
  - provider: GitHub
    release: $(appveyor_repo_tag_name)
    description: |
      Hunspell binary for Windows 64-bit.

      Built https://github.com/hunspell/hunspell at commit `$(GITCOMMIT_FULL)`.

      | File                            | SHA-256 sum |
      | ---                             | ---         |
      | hunspell-$(HUNSPELL_VERSION).7z | `$(ARTIFACT_HASH)` |
    auth_token:
      secure: zrCvgZYRklwG2hyVIxJq4dtx0NDXFvYjUdW27htBD/j4Anp07P+3zSFnwXDR1QJ7
    artifact: hunspell-$(HUNSPELL_VERSION).7z,sha256sum.txt
    on:
      branch: master
      appveyor_repo_tag: true
